version: '3.4'

services:

  fastapi:
    build:
      context: .
      dockerfile: FastApiDockerfile
    ports:
      - 8000:8000
    container_name: fastapi

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=elyadata
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  angular:
    build:
      context: .
      dockerfile: angularDockerfile
    ports:
      - 4200:4200
    container_name: angular
